rm(list = ls())
#memory.limit(size=20000)
library(tidyverse)
library(lubridate)
library(caret)
library(survival)
library(Hmisc)
#library(rms)
setwd("C:/Users/ngocdung/Dropbox/Front-end developer/src/data-science-path/udacity-nanodegree/Project 3/Assignment")
train <- read.csv("./Creditworthiness/credit-data-training.csv", stringsAsFactors=F)
test <- read.csv("./Creditworthiness/customers-to-score.csv", stringsAsFactors=F)
glimpse(train)
glimpse(test)